platform :ios, '11.0'
use_frameworks!

target 'DatadogSDKBridge_Tests' do
  # Uncomment the `pod DatadogSDK` below to build against the local version of `dd-sdk-ios` (requires `pod update`).
  # This might be handy to work on the bridge without releasing a new version of `dd-sdk-ios`.
  #
  # Otherwise `pod update` will use `dd-sdk-ios` version specified as dependency in `DatadogSDKBridge.podspec`.
  # pod 'DatadogSDK', :path => '../../dd-sdk-ios/'

  pod 'DatadogSDKBridge', :path => '../'
end

post_install do |installer|
  # Enable `DD_SDK_COMPILED_FOR_TESTING` condition when compiling `DatadogSDK` dependency:
  datadog_sdk_target = installer.pods_project.targets.detect {|t| t.name == "DatadogSDK" }
  datadog_sdk_target.build_configurations.each do |config|
    config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DD_SDK_COMPILED_FOR_TESTING'
  end
end
